services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm-db-init:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - "./db/srcs:/var/db_src"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

